import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const src = path.resolve(here, '../src')
const read = relative => fs.readFileSync(path.join(src, relative), 'utf8')

test('business modules use the archive workspace shell instead of the legacy tab chrome', () => {
  const app = read('App.vue')
  const shell = read('analysis-os/components/ArchiveWorkspaceShell.vue')

  assert.match(app, /ArchiveWorkspaceShell/)
  assert.match(app, /v-if="preparedModule"/)
  assert.match(app, /:active="Boolean\(activeModule\)"/)
  assert.match(app, /QuotePage v-else-if="workspaceRenderRoute === '智能报价'"/)
  assert.match(app, /TrendPage v-else-if="workspaceRenderRoute === '市场趋势预测'"/)
  assert.match(app, /ScheduledTasksPage v-else-if="workspaceRenderRoute === '定时任务'"/)
  assert.doesNotMatch(app, /QuotePage v-if="visitedTabs\.has\('智能报价'\)"/)
  assert.match(app, /@return="returnToArchive"/)
  assert.match(app, /@navigate-module="navigateWorkspace"/)
  assert.match(app, /'管理后台': \(\) => import\('\.\/components\/AdminView\.vue'\)/)
  assert.match(app, /workspaceRenderRoute === '管理后台'/)
  assert.match(app, /ADMIN_WORKSPACE_MODULE/)
  assert.doesNotMatch(app, /<AppTabs/)
  assert.match(shell, /搜索证券、数据或命令/)
  assert.match(shell, /class="global-rail"/)
  assert.match(shell, /class="entity-bar"/)
  assert.match(shell, /class="entity-views"/)
  assert.match(shell, /class="workspace-function-menu"/)
  assert.match(shell, /v-for="group in moduleGroups"/)
  assert.match(shell, /function-menu-popover/)
  assert.match(shell, /class="entity-switcher entity-context-display"/)
  assert.doesNotMatch(shell, /aria-label="打开行情"/)
  assert.doesNotMatch(shell, /aria-label="打开研究助手"/)
  assert.doesNotMatch(shell, /aria-label="打开模拟盘"/)
  assert.doesNotMatch(shell, /查看行情|查看财务|进入研究|查看风险/)
  assert.doesNotMatch(shell, /context-popover/)
  assert.match(shell, /navigateHistory/)
  assert.match(shell, /navigate-module/)
  assert.doesNotMatch(shell, /legacy-admin/)
  assert.doesNotMatch(shell, /旧版后台/)
  assert.match(shell, /NotificationCenter/)
  assert.match(shell, /handleNotificationNavigate/)
  assert.match(shell, /data\/moduleNav/)
  assert.match(shell, /buildModuleNavGroups/)
  assert.doesNotMatch(shell, /module-index-bar/)
  assert.match(shell, /workspace-shell\.preparing/)
  assert.match(shell, /position: fixed; inset: 0; z-index: 100/)
  assert.match(shell, /opacity: 0;\s*pointer-events: none/)
  assert.doesNotMatch(shell, /workspace-entry-bridge/)
  assert.doesNotMatch(shell, /entry-hud/)
  assert.match(shell, /--panel: #efebe3/)
  assert.match(shell, /--radius: 7px/)
})

test('local preview bypass is development-only and restricted to localhost', () => {
  const app = read('App.vue')

  assert.match(app, /import\.meta\.env\.DEV/)
  assert.match(app, /host === '127\.0\.0\.1'/)
  assert.match(app, /host === 'localhost'/)
  assert.match(app, /params\.get\('preview'\) === '1'/)
  assert.match(app, /previewMode\.value = true/)
  assert.match(app, /preview@local\.test/)
  assert.doesNotMatch(app, /previewMode\.value = true[\s\S]{0,200}session\.restore\(\)/)
})

test('global research context is shared by market and execution workspaces', () => {
  const app = read('App.vue')
  const store = read('analysis-os/state/researchContext.js')
  const market = read('pages/MarketPage.vue')
  const cross = read('components/CrossMarketView.vue')
  const sim = read('components/SimTradeView.vue')
  const ai = read('components/AiCenter.vue')
  const chain = read('pages/ChainPage.vue')
  const risk = read('pages/RiskPage.vue')
  const financial = read('pages/FinancialReportPage.vue')

  assert.match(store, /const context = ref\(null\)/)
  assert.match(store, /function setContext/)
  assert.match(app, /:context="researchContext"/)
  assert.match(app, /@context-change="setResearchContext"/)
  assert.match(market, /context-change/)
  assert.match(cross, /context-change/)
  assert.match(sim, /context-change/)
  assert.match(app, /<AiCenter :research-context="researchContext"/)
  assert.match(app, /<ChainPage[^>]*:research-context="researchContext"/s)
  assert.match(app, /<RiskPage[^>]*:research-context="researchContext"/s)
  assert.match(app, /<FinancialReportPage[^>]*:research-context="researchContext"/s)
  assert.match(ai, /引用当前对象/)
  assert.match(chain, /研究上下文/)
  assert.match(risk, /compatibleRiskContext/)
  assert.match(risk, /不自动伪造风险样本/)
  assert.match(financial, /公司上下文/)
  assert.match(financial, /不自动生成财务数字/)
})

test('strategy handoff carries real questionnaire intent into backtest without inventing MA parameters', () => {
  const app = read('App.vue')
  const store = read('analysis-os/state/workflowHandoff.js')
  const strategy = read('pages/StrategyPage.vue')
  const backtest = read('pages/BacktestPage.vue')

  assert.match(store, /const backtestHandoff = ref\(null\)/)
  assert.match(store, /function setBacktestHandoff/)
  assert.match(strategy, /发送到回测/)
  assert.match(strategy, /maxDrawdownPct/)
  assert.match(strategy, /allocation: allocation\.value\.map/)
  assert.doesNotMatch(strategy, /short_ma|long_ma/)
  assert.match(app, /@send-backtest="sendStrategyToBacktest"/)
  assert.match(app, /:handoff="backtestHandoff"/)
  assert.match(backtest, /导入的策略意图/)
  assert.match(backtest, /策略问卷不会自动改写双均线参数/)
  assert.match(backtest, /应用本金/)
})

test('industry workspace keeps a graph-first structural canvas without presenting scaffold edges as verified facts', () => {
  const chain = read('pages/ChainPage.vue')

  assert.match(chain, /产业结构/)
  assert.match(chain, /class="graph-stage"/)
  assert.match(chain, /class="graph-node"/)
  assert.match(chain, /glass-dormant/)
  assert.match(chain, /chain-glass-rise/)
  assert.match(chain, /backdrop-filter: blur\(14px\)/)
  assert.match(chain, /const analysisPhase = ref\('idle'\)/)
  assert.match(chain, /runAnalysisAnimation/)
  assert.match(chain, /propagationWaves/)
  assert.match(chain, /class="edge-scan"/)
  assert.match(chain, /class="analysis-status-overlay"/)
  assert.match(chain, /class="chain-analysis-plan"/)
  assert.match(chain, /graph-ambient-field/)
  assert.match(chain, /prefers-reduced-motion: reduce/)
  assert.match(chain, /结构索引不代表已验证的具体供应关系/)
  assert.match(chain, /模型分析原文，不从文本中伪造结构化关系/)
  assert.match(chain, /查看节点详情/)
  assert.match(chain, /node-file\.open/)
})

test('archive transition is progress-driven and preserves the extracted card for workspace return', () => {
  const transition = read('analysis-os/motion/useArchiveTransition.js')
  const scene = read('components/analysis/AnalysisArchiveScene.vue')
  const page = read('pages/AnalysisOsPage.vue')

  assert.match(transition, /EXTRACTING/)
  assert.match(transition, /WORKSPACE_ACTIVE/)
  assert.match(transition, /RETURN_ALIGN/)
  assert.match(transition, /RETURN_DESCEND/)
  assert.match(scene, /0\.40 \+ extraction \* \(4\.05 - 0\.40\)/)
  assert.match(scene, /camera\.position\.copy\(cameraBase\)\.lerp\(cameraDetailBase, detail\)/)
  assert.match(page, /archiveTransition\.enter/)
  assert.match(page, /archiveTransition\.returnToArchive/)
})

test('keyboard navigation covers archive rows, workspace escape, and focus restoration targets', () => {
  const page = read('pages/AnalysisOsPage.vue')
  const shell = read('analysis-os/components/ArchiveWorkspaceShell.vue')

  assert.match(page, /event\.key === 'ArrowUp'/)
  assert.match(page, /event\.key === 'ArrowDown'/)
  assert.match(page, /navigateBySteps\(delta, 'module-row-step'\)/)
  assert.match(page, /wrap\(focusedIndex\.value \+ delta, modules\.length\)/)
  assert.match(page, /\.focus\?\.\(\{ preventScroll: true \}\)/)
  assert.match(shell, /event\.key !== 'Escape'/)
  assert.match(shell, /requestReturn\(\)/)
  assert.match(shell, /tabindex="-1"/)
  assert.match(shell, /moduleTitleRef/)
})

test('sleep and wake remain a visual layer over the logical archive selection', () => {
  const idle = read('analysis-os/motion/useArchiveIdle.js')
  const scene = read('components/analysis/AnalysisArchiveScene.vue')
  const page = read('pages/AnalysisOsPage.vue')

  assert.match(idle, /dimStartMs: 8_000/)
  assert.match(idle, /motionStartMs: 12_000/)
  assert.match(idle, /sleepStartMs: 18_000/)
  assert.match(idle, /SLEEP_DRIFT/)
  assert.match(scene, /sleepOffsets/)
  assert.match(scene, /captureSleepPosition/)
  assert.match(page, /__jarvisArchiveDebug/)
})

test('representative workspace pages keep stable product headings during the professional workspace migration', () => {
  assert.match(read('pages/MarketPage.vue'), /<h1>\{\{ focusedTitle \}\}<\/h1>/)
  assert.match(read('components/CrossMarketView.vue'), /<h1>多市场<\/h1>/)
  assert.match(read('pages/BacktestPage.vue'), /<h1>回测<\/h1>/)
  assert.match(read('components/SimTradeView.vue'), /<h1>操作终端<\/h1>/)
  assert.match(read('components/AiCenter.vue'), /contextTarget \|\| '研究助手'/)
  assert.match(read('components/AiCenter.vue'), /class="evidence-dock"/)
  assert.match(read('components/AiCenter.vue'), /class="research-canvas"/)
  assert.match(read('components/AiCenter.vue'), /class="context-inspector"/)
  assert.match(read('pages/SentimentPage.vue'), /<h1>多空研报<\/h1>/)
  assert.match(read('pages/FinancialReportPage.vue'), /<h1>财报解析<\/h1>/)
  assert.match(read('pages/ChainPage.vue'), /<h1>产业链图谱<\/h1>/)
  assert.match(read('pages/RiskPage.vue'), /<h1>风险预警<\/h1>/)
  assert.match(read('pages/StrategyPage.vue'), /<h1>策略生成<\/h1>/)
  assert.match(read('components/OpsView.vue'), /<h2>运维<\/h2>/)
})

test('fluid terminal P0 uses Apple interaction materials while preserving Rhine identity', () => {
  const shell = read('analysis-os/components/ArchiveWorkspaceShell.vue')
  const system = read('analysis-os/styles/WorkspaceSystem.css')
  const market = read('pages/MarketPage.vue')
  const ticker = read('components/market/QuoteStrip.vue')

  assert.match(shell, /--material-glass:/)
  assert.match(shell, /--material-elevated:/)
  assert.match(shell, /--motion-standard:/)
  assert.match(shell, /styles\/WorkspaceSystem\.css/)
  assert.match(system, /--ds-motion-state:/)
  assert.match(system, /--ds-focus-shadow:/)
  assert.match(system, /--ds-selection-surface:/)
  assert.match(shell, /class="command-search-row"/)
  assert.match(shell, /研究对象/)
  assert.match(shell, /data-command-kind/)
  assert.match(shell, /搜索标的、工作区或操作/)
  assert.match(shell, /event\.key === '\/'/)
  assert.match(shell, /event\.key === 'ArrowDown'/)
  assert.match(market, /class="floating-chart-toolbar"/)
  assert.match(market, /class="toolbar-popover period-popover"/)
  assert.match(market, /class="toolbar-popover sample-popover"/)
  assert.match(market, /class="market-rail market-inspector"/)
  assert.match(market, /inspector-collapsed/)
  assert.doesNotMatch(market, /MARKET \/ LIVE BOARD|PRIMARY CANVAS|QUOTE RAIL|DATA HEALTH/)
  assert.match(ticker, /market-ticker/)
  assert.match(ticker, /transform: scale\(\.98\)/)
})

test('workspace navigation popovers escape the horizontal nav stacking context', () => {
  const shell = read('analysis-os/components/ArchiveWorkspaceShell.vue')
  const system = read('analysis-os/styles/WorkspaceSystem.css')

  assert.match(shell, /function alignPopover\(details\)/)
  assert.match(shell, /@scroll\.passive="alignOpenPopovers"/)
  assert.match(shell, /\.function-menu-popover\s*\{[\s\S]*position:\s*fixed/)
  assert.match(shell, /\.split-popover\s*\{[\s\S]*position:\s*fixed/)
  assert.doesNotMatch(system, /\.entity-views\s*\{[^}]*isolation:\s*isolate/)
  assert.doesNotMatch(system, /\.workspace-function-menu[^}]*z-index:/)
})

test('research assistant accepts local documents and keeps the research document expanded', () => {
  const ai = read('components/AiCenter.vue')

  assert.match(ai, /extractFinancialDocument/)
  assert.match(ai, /aria-label="上传研究文件"/)
  assert.match(ai, /上传文件/)
  assert.match(ai, /researchAttachments/)
  assert.match(ai, /buildAttachmentContext/)
  assert.match(ai, /hiddenContent \|\| content/)
  assert.match(ai, /\.research-document\s*\{[\s\S]{0,180}?flex:\s*0 0 auto/)
  assert.match(ai, /\.research-document\s*\{[\s\S]{0,220}?overflow:\s*visible/)
  assert.match(ai, /\.research-canvas\s*\{[\s\S]{0,220}?overflow-y:\s*auto/)
})

test('strategy inputs and research quick peek share the fluid interaction system', () => {
  const strategy = read('pages/StrategyPage.vue')
  const choice = read('components/common/ChoicePopover.vue')
  const ai = read('components/AiCenter.vue')

  assert.match(strategy, /ChoicePopover/)
  assert.match(choice, /choice-popover-menu/)
  assert.match(choice, /--material-elevated/)
  assert.match(ai, /var\(--material-glass/)
  assert.match(ai, /source-peek-in/)
})

test('workspace navigation restores the current session without persisting across accounts', () => {
  const tabs = read('composables/useWorkspaceTabs.js')

  assert.match(tabs, /sessionStorage\.setItem/)
  assert.match(tabs, /jarvis-workspace-session:/)
  assert.match(tabs, /user\?\.id \|\| user\?\.email \|\| user\?\.username/)
  assert.match(tabs, /restoreSession/)
  assert.doesNotMatch(tabs, /localStorage\.setItem/)
})
